services:
    postgres:
        image: postgres:17.3
        container_name: nguyenhanhstore_postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: postgres
            POSTGRES_DB: NguyenHanhStore
        ports:
            - "5433:5432"
    backend:
        image: nguyentienminh0710/nguyenhanhstore_clothes:0.0.1
        restart: always
        container_name: nguyenhanhstore_backend
        env_file: ".env"
        environment:
            POSTGRES_HOST: postgres
        ports:
            - "3000:3000"